# PROBLEM: biggest palindrome number generated by the product of 2 3-digit numbers
# STATUS: solved!
# AUTHOR: KeizerZilla

# function is_palindrome(n)
# returns True is n is a palindromic number, False otherwise

def is_palindrome(n):
    pal = str(n)


    for i in range(0, int(len(pal) / 2)):
        if pal[i] != pal[len(pal) - 1 - i]:
            return False

    return True

# main code

max_prod = 0
prod = 0

for x in range(100, 1000):
    for y in range(100, 1000):
        prod = x * y
        if is_palindrome(prod) and prod > max_prod:
            max_prod = prod

print(str(max_prod))
